# Generated by Django 2.1.2 on 2018-11-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RhubarbTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('name', models.CharField(max_length=128, verbose_name='название задачи')),
                ('params', models.TextField(help_text='JSON, удовлетворяющий схеме задачи.', verbose_name='параметры')),
                ('result', models.TextField(blank=True, verbose_name='результат выполнения')),
                ('is_done', models.BooleanField(default=False, verbose_name='выполнена?')),
            ],
            options={
                'verbose_name': 'задача',
                'verbose_name_plural': 'задачи',
                'ordering': ('created',),
            },
        ),
    ]
